aquietone/lootnscoot

init.lua
loot_hist.lua

Been testing this for the last few days on Lazarus. 
Mostly testing in LDON dungeons and tributing and selling after.

some tweaks

---

init.lua

if we are using actors. pass that to looted and we won't use link lookups with LinkDB since we are passing the link directly through actors.
Added toggles to the loot n scoot menu pushed to looted. to easily toggle settings on or off.

pass useactors

---

init.lua

fix for toggles only saving the autodestroy setting.

toggle fix

---

init.lua
loot_hist.lua

Added Report GUI to looted. 
* Accepts evaluation from lootnscoot over actors. 
* Displays what the evaulation was when the item was looted. 
* Allows you to change the Rule for the item with a right click.
* Left Click opens link.
Video in action:
https://vimeo.com/948190154?share=copy

Pass eval value

---

loot_hist.lua

I forgot to remove the theme stuff when i copied in the new version of looted.
this fixes that.

fix: removed theme stuff

---

init.lua

if enabled will try to restock items from the current vendor after selling.

feat: auto restock option

---

init.lua

/lootutils settings
will toggle the settings and loot tables gui. so you can modify the settings in game.

feat: Settings and loot table GUI

---

init.lua

this fixes the primary key issue when updating items.

Fix db primary key

---

init.lua

fix: Forgot Normal_Rules had Global 2x

---

init.lua
loot_hist.lua

* removed a bunch of unused code
* moved looted config so it doesn't get corrupted.
* cleanup some reporting

fix: some fixes and cleanup

---

init.lua

for handling calling LNS from its install folder and not being bundled You can call it in directed mode either way by bundling it into your lib/lootnscoot folder or just pass lootnscoot as the 3rd parameter to call it from its own standalone install folder (this should make it easier than having to maintain LNS inside other scripts)

directed adjustments

---

init.lua

* New Setting `MaxCorpsesPerCycle` sets the number of corpses we will try to loot each cycle,
* fixed some history reporting outputs, they would record correctly but display wrong on the session.
* Made the debug button a toggle for easier visibility

new setting and some fixes \ tweaks

---

init.lua
lib/Write.lua

fixes some value mismatch crashes and some typo's
added `LootCheckDelay` Setting this is how long in seconds we will wait before trying to check corpses again.
cleaned up the loot my corpse checks and when we do the looting.

fix: bug fixes and new setting

---

init.lua

- Removes duplicated messaging between script `lootnscoot` and script `DirectorLNSPath`. Looks like rgmercs is moving away from having a custom path anyways, but maybe someone else will still want to use a non-default path to LNS for some reason.
- Since rgmercs is moving away from embedding LNS, change `LNS.DirectorLNSPath` to only be set if 3rd arg is provided, otherwise it remains `nil` and messages go to `lootnscoot` script.
- If sending to `loot_module`, script is `LNS.DirectorScript`.
- If sending to `looted`, script is `LNS.DirectorLNSPath` or `lootnscoot`.
- If sending to `lootnscoot`, script is `LNS.DirectorLNSPath` or `lootnscoot`.

remove duplicate actor messages

---

init.lua

remove duplicate actor messages (#30)
Added help window with lists of commands and settings. `/lns help` or there is a toggle on the main UI
`/lns bank` was a duplicate command
now to bank with targeted banker use `/lns bankstuff`
`/lns bank` is still reserved for setting items on cursor or specified items rule to Bank

feat: Help WINDOW, fix: restock fixes

---

init.lua

should no longer have cross server talk with chars having the same names.
`local eqServer  = string.gsub(mq.TLO.EverQuest.Server(), ' ', '_')` Format Server Name to match LNS
if directing:
if the message is missing `Server = eqServer` in the message body it will process normally if its present we will make sure it matches our server before proceeding

fix: cross server talk

---

init.lua

forgot to commit before the pr

rehash last commit

---

init.lua

after thinking about this the entire 200mile drive there and 2 days of camping...
complete redo of the getRule function
cleaner, easier to work through. Now with Less Spaghetti!
no drop items will not create an initial rule if `lootNoDrop` and `lootNoDropNew` are NOT both enabled. this will keep it as NEW for all chars until the rule is confirmed.

ref: refactor decision making

---

init.lua
loot_hist.lua

you can now look up items in the items table by fields using operators (< > = <= >=)
example hp>=500
will return items with hp value greater than or equal to 500
you can also multi search to refine
put the searches inside {} separated by a comma
example {hp>=500, hp<1000, strength>20}
this will return items with hp values from 500 - 999 and only with strength values of 20 +

item lookup search

---

init.lua

[hp>=500, name~robe}
will show items with 500 or more hp and have robe in the name.
~ acts as a partial match

add ~ symbol for a like compare

---

init.lua
loot_hist.lua

You can also do multi searches by placing them in { } curly braces and separated by either ( , or | ) a comma will be treated as AND in the search while a pipe ( | ) will be treated as OR
example: {hp>=500, ac<=100} this will return items with hp values of 500 and up, and ac values of 100 and below
example: {name~"words of" | name~"rune of"} will find items with either "words of" or "rune of" in the name

Search OR option

---

init.lua

fix bug where new rules weren't auto adding but manual additions were.

fix: new rule add
